language: objective-c
cache: cocoapods
before_install:
- chmod +x fastlane/travis.sh
before_script:
- openssl aes-256-cbc -k $ENCRYPT_PASSWORD -in fastlane/Certificates/distribution.p12.enc
  -d -a -out fastlane/Certificates/distribution.p12
script:
- pod --version
- "./fastlane/travis.sh"
after_success: 
after_script: 
osx_image: xcode7.3
xcode_workspace: HelloWorld.xcworkspace
xcode_scheme: HelloWorld
xcode_sdk: iphonesimulator9.3
env:
  global:
  - secure: rD2CyfnvjLlOmo09+8mUlja8Sf0eaasgh+nPQV3l/1S5y8/sUFaqnXYZwhZVFOYt48Yrpb1hNzpVRk07kH91aM2mCzwmJnvjYOxofjTtINpHX4f5aA4hKZqJ+0cfqfeO62Y4clBJQ+cys+dQlI2gUb8k41JYPvJ4RfoJ7XkzNUKMWFXOHgPvT/cKi25KTJzh8F6hkb3oIV9UCC07nKhTh2sQtYXebKqRpQzAQqvg926tyznHLx1lcbZQeCrU5W1zjM/7Hz7wXSFSd5QvMxzN4SAn4a0+bsLQMpMSlSXOWRd8vWrK8Q2fbnRRXUxzZc1EiVFxjXTflTjgqYUMVs7uhHKsQuxKtjkcf23ay03s0abDv1NeHxy7niB6AIWK7lKzNQR4E08A5OqPuYaWrv07rjdblrySc6VmYE/dVmZs0lcmOmblUZW8HR7izFjDYrSSTyFAPSlqhsaSHLwSz+NRxwqIRDjroM+KaInJTYCZEV1KyZwhc6UVANggm+nF0HdhLg1llWoFNw7MWHOu0twZMetbcoJRVrNj9nOYvy4EPkkW2IsrpvNrO+YekgXH37Rgjk5+r/ON0xBjd8DRWWibel//xrmm4yV5oK7S9VA/rImwvuRJWUZharZWYp5/1/o/7BkpPESifzs0bwxZ8fZF/VW213GTQfKizSzGroU0T1k=
  - secure: A0lG6OLCiSXgiHe+Vu7se60j947SYx/88DQwpSyN/K0/yAqYuYwoBKoYeojn+bzNx8zlZpE0Rg0g2c5oQM/DMgOIaKNUSKd+W+OpB+qFyNo6F5hmpBbXTNETAAmYNy5Yjg08oiv/q+OVXUlzeYG8jbUwU/Aqhr7ASriqWcyEW87TAluIFxbwxeD0NMwSoeLkN5FrYkDR5ecX6PP1RLcbsM7FargQ2WzqozQZvPBSjYwuC9reInG0Op01GIkd0QioLEU66DPg6PDxdG3aNeAfxrvztp5QFCZ3PFNRtmV/qPNbKHXqgAroEneNfW6G9OVWyjwS2B2s5qvU2TTgCDK3Ll/uMSfpj4LWFYYbmc79fLtICK+0aobLnqTg++KoDudfJ18lmtl+eSgHUNAOX6schA8Krw64ErEFLdvpnZ17nEMag/7Obm/4OD0IACJdZ8D8Kkm3Xa7ihRU5OU6MPOtdARdK2Yvv5wMk2IYP6kG9NyqZxVmxCbcU500sislOOg7Bzn1r/T5iZvp6UF7jyO7E9k+gG4RLjxqraCquzk41FEvv5Ayavi6m2ERDetDYsjmblhkvh7wg62QsRX42GTw0JxgU3rN8fU2kb+48TBIfB8WkQ19cjelYYtU1atpHT5iwqfO9lZz7AuqsDsiZ3UK6M4cdtVhK1CsbIKQNTGaJtIk=
  - secure: pSNCFwSQND1rsbVJYID98fvCgDICQKSr0x55pKHvBIi74a8QvVRln6RAK6YUJeZCubUatIYdOIxmqkboaNHzwbxSm4vGrC5qm4iUjn+XYMwh9WIgRS+uIr+CRnPdfYPbZaJMJ7QL217aF0mc/ZwYLbqY7FwRktux4Hlbxn27xiB9enu3OxEFcSgBiyCifFgUq1Nji6Edye2RIR9BHAxSyz3pOfdk9XzzKylZrL6VpTFkdDZcaBCu4otlDmViRKCjXaT1WJ5Mlraw8BLnfKw4e7VFukGQgEH05Ky9A8h2kv12IwcndXcYw45jFrsv36H/4oUFT/JWhgjlawOzuJRpWdgyYjjWaUqe52fDB4iARtoRWJSsSVpk4ABuBAo1xiGbnVS4Pch5UHxlDhATZ4DSssRUfvbJFr9QMT8gTrTTqLk6UMqs0bboGlTIBSQkXTy1dGy42Hje9yOcs6Ki6OAHE4IhWAswoA9lZ7tNryhUbr+kvCRMusY3L+OST012h7Wm93DVN8XQ4xGsKvnXKA13A9pwAc6yPL9LBz58PMHtVAf05wdPrSgq2KB46gyxt1Ngzu3X2lpbKbAQk4fzo+nRKd5FGrV67umKcOTiVFpxdqcarLQjB+Q6EiQNVV9XQsDimbW1QGQeiN7/MSSkYIbG5qPegJ9tSfsUucV3ejM0YwA=
